/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "resmerge"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "resmerge"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.1"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * output_arg;	/**< @brief output file name. If a single directory <dirname> is specified then the default output file name is  <dirname>.cnl.
  NOTE: the number of nodes is written to the output file only if the node base synchronization is applied, otherwise 0 is set (default='clusters.cnl').  */
  char * output_orig;	/**< @brief output file name. If a single directory <dirname> is specified then the default output file name is  <dirname>.cnl.
  NOTE: the number of nodes is written to the output file only if the node base synchronization is applied, otherwise 0 is set original value given at command line.  */
  const char *output_help; /**< @brief output file name. If a single directory <dirname> is specified then the default output file name is  <dirname>.cnl.
  NOTE: the number of nodes is written to the output file only if the node base synchronization is applied, otherwise 0 is set help description.  */
  int rewrite_flag;	/**< @brief rewrite already existing resulting file or skip the processing (default=off).  */
  const char *rewrite_help; /**< @brief rewrite already existing resulting file or skip the processing help description.  */
  long btm_size_arg;	/**< @brief bottom margin of the cluster size to process (default='0').  */
  char * btm_size_orig;	/**< @brief bottom margin of the cluster size to process original value given at command line.  */
  const char *btm_size_help; /**< @brief bottom margin of the cluster size to process help description.  */
  long top_size_arg;	/**< @brief top margin of the cluster size to process (default='0').  */
  char * top_size_orig;	/**< @brief top margin of the cluster size to process original value given at command line.  */
  const char *top_size_help; /**< @brief top margin of the cluster size to process help description.  */
  float membership_arg;	/**< @brief average expected membership of the nodes in the clusters, > 0, typically >= 1 (default='1').  */
  char * membership_orig;	/**< @brief average expected membership of the nodes in the clusters, > 0, typically >= 1 original value given at command line.  */
  const char *membership_help; /**< @brief average expected membership of the nodes in the clusters, > 0, typically >= 1 help description.  */
  char * sync_base_arg;	/**< @brief synchronize node base with the specified collection.  */
  char * sync_base_orig;	/**< @brief synchronize node base with the specified collection original value given at command line.  */
  const char *sync_base_help; /**< @brief synchronize node base with the specified collection help description.  */
  int extract_base_flag;	/**< @brief extract the node base from the clusterings instead of merging the clusterings (default=off).  */
  const char *extract_base_help; /**< @brief extract the node base from the clusterings instead of merging the clusterings help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int rewrite_given ;	/**< @brief Whether rewrite was given.  */
  unsigned int btm_size_given ;	/**< @brief Whether btm-size was given.  */
  unsigned int top_size_given ;	/**< @brief Whether top-size was given.  */
  unsigned int membership_given ;	/**< @brief Whether membership was given.  */
  unsigned int sync_base_given ;	/**< @brief Whether sync-base was given.  */
  unsigned int extract_base_given ;	/**< @brief Whether extract-base was given.  */

  char **inputs ; /**< @brief unamed options (options without names) */
  unsigned inputs_num ; /**< @brief unamed options number */
  int exrtact_mode_counter; /**< @brief Counter for mode exrtact */
  int sync_mode_counter; /**< @brief Counter for mode sync */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
